name: beat_this
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.11
  - pytorch=2.3.1
  - pytorch-cuda=12.1
  - torchaudio=2.3.1
  - soxr-python
  - einops
  - pip:
    - numpy
    - rotary-embedding-torch
    - librosa
    - matplotlib
    - pydub